### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by rundtjan** [hanrastic/RSA-Cryptosystem#1]
Koodi näyttää hyvältä ja selkeältä, ja RSA-salaus näyttää toimivan määrittelyjen mukaisesti. Hienoa, että käyttäjä pystyy valitsemaan minkä pituisen avaimen haluaisi saada. 

Kommentteja:
- alkulukuja generoidessa, voisit harkita sitä, että olisiko p ja q hieman erikokoisia. Ymmärtääkseni, tämä parantaa RSA-salauksen turvallisuutta.
- enkryptauksessa ja dekryptauksessa, voisit harkita sitä, että käyttäisitkö jonkin padding-menetelmän.
- enkryptaus tällä hetkellä ei rajaa viestin pituutta, eikä jaa sitä pienempiin osiin. Ymmärtääkseni, RSA-salauksessa, viestin bittipituus täytyy olla lyhyempi kuin julkisen avaimen bittipituus. Voisit ehkä harkita viestin pilkkomista osiin ennen salausta.
- ohjeet, koodin dokumentaatio yms. ovat varmasti tulossa myöhemmässä vaiheessa. En saanut esim. testejä ajettua, siitä jokin mainita, eli missä kannattaa mitä komentoa ajaa, voisi olla hyvää.

Muuten kaikki oli siistiä ja vaikutti toimivan hyvin näppärästi ja nopeasti.

**Comment by hanrastic** [comment]
Kiitos hyödyllisistä kommenteista!
