### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by SiniCode** [hanrastic/RSA-Cryptosystem#2]
Projekti ladattu 29.4. klo 15.00

# Käyttökokemus ja sovelluksen toiminta
- Koodin lataaminen omalle koneelle ja sovelluksen käynnistäminen onnistui hyvin ohjeiden mukaan. Vain zip-kansion purkaminen puuttuu ohjeista, mutta ehkä sen voi olettaa itsestään selväksi.
- Yksinkertainen käyttöliittymä, jolla voi testata, että avainten luominen, salaus ja sen purku toimivat oikein.
- Lyhyillä viesteillä toimii hienosti, mutta jos viesti on esim. "a" * 130, tulee UnicodeDecodeError 1024-bittisellä avaimella. Pidemmällä avaimella onnistuu pidempi viesti, mutta ei kuitenkaan kovin montaa riviä. Pitkien viestien pilkkominen ja salaaminen/purkaminen osissa voisi auttaa.
- Paljon tapahtuu käyttäjältä piilossa. Esim. avaimia ei näe, jolloin niitä ei myöskään saa talteen eikä voi jakaa (kuten voisi haluta, jos sovellusta oikeasti käyttäisi muuhunkin kuin algoritmien testaamiseen).
- Oikeassa käytössä olisi myös hyvä, että käyttäjä voisi antaa haluamansa avaimen salauksessa ja purkaa minkä tahansa salatun tekstin antamalla oikean avaimen.
- Hienoa, että sovellus ei kaadu, vaikka käyttäjä syöttäisi jotakin odottamatonta valikkotilanteissa.
- Jos aikaa riittää, voisi kokeilla toteuttaa myös jonkinlaisen paddingin. Se parantaisi salauksen turvallisuutta, koska silloin ei voi vain arvailla, mitä viestissä lukee, ja katsoa, saako salaamalla saman tuloksen. Toki tässä sovelluksessa, kun avaintakaan ei näe, ei voi myöskään näin arvailla.
- Yksi pieni kirjoitusvirhe käyttöliittymässä, joka näkyy käyttäjälle: app.py, rivi 40: Encrypt-sanasta puuttuu r

# Koodi
- Koodi on jaettu järkevästi omiin tiedostoihin, luokkiin ja metodeihin.
- Käyttöliittymän koodi on kaikki yhdessä pötkössä, sitä voisi vielä halutessaan jäsennellä paremmin. Käyttöliittymä ei myöskään ole tällä hetkellä oma luokkansa toisin kuin kaikki muu sovelluksessa, vaan oikeastaan vain yksi funktio.
- Koodi on dokumentoitu #kommenteilla, mikä auttaa lukijaa pysymään kärryillä siitä, mitä missäkin tapahtuu. Docstring-dokumentaatiolla olisi omat hyvät puolensa, joihin kannattaa tutustua, jos ei vielä ole ollut käytössä, mutta ei varmaan välttämätöntä tähän projektiin. Mahdollista jatkokehitystä ajatellen dokumentaatiossa olisi myös hyvä kirjoittaa auki,
mitä mikäkin funktio odottaa annettavan argumentteina ja mitä se palauttaa.
- key_generator.py, rivi 64: Onko else sisennetty oikein?

# Testaus
- Yksikkötestit käytössä, pystyy ajamaan annettujen ohjeiden mukaan ja menevät läpi.
- assertTrue(test_value) voisi käyttää assertEqual(True, test_value) sijaan
- assertIsInstance(test_value, int) voisi käyttää assertEqual(type(test_value), int) sijaan
- Testausdokumenttiin voisi sisällyttää jonkin taulukon tai tai muun vertailun siitä, miten kauan eripituisten avainten luominen kestää.

# Yhteenveto
Projekti on jo pitkällä ja varmaan jo tällaisenaan hyvin täyttää kurssin vaatimukset. Oman harkinnan ja innostuksen mukaan voisi vielä miettiä toteutusta pidemmille viesteille ja/tai paddingille. Hyvää työtä!

**Comment by hanrastic** [comment]
Kiitos kattavasta katselmoinnista!
